name: Continuous Deployment

on:
  pull_request:
    branches:
      - release

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build:ts

      - name: Create env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo POSTGRES_URI={{ secrets.POSTGRES_URI }} >> .env
          echo IGDB_CLIENT_ID={{ secrets.IGDB_CLIENT_ID }} >> .env
          echo IGDB_CLIENT_SECRET={{ secrets.IGDB_CLIENT_ID }} >> .env

      - name: Run application
        run: |
          pm2 stop addallthethings
          pm2 start dist/src/server.js --name addallthethings