name: Continuous Deployment

on:
  pull_request:
    branches:
      - release

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build:ts